OBJ     =       ogrmapgisdriver.obj ogrmapgisdatasource.obj ogrmapgislayer.obj
        
EXTRAFLAGS =	-I.. -I..\..

GDAL_ROOT	=	..\..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	$(OBJ)

clean:
	-del *.obj *.pdb



